### ISSUE TITLE
Please setup HTTPS on http://downloads.libremesh.org/

### ISSUE THREAD

**Issue by PabloCastellano** [libremesh/lime-web#10]
That subdomain contains firmware images and without https it's easy to distribute trojanized images in certain cases. You can use Let's Encrypt which for ease and free-of-charge.

Have a look at https://certbot.eff.org/ for the setup.

**Comment by nicopace** [comment]
@p4u can we set this up? I can do it if I get access to it ;)

**Comment by ilario** [comment]
Right now downloads.libremesh.org has a let's Encrypt certificate. But it's expired... @p4u ?

**Comment by gmarcos87** [comment]
@ilario https://downloads.libremesh.org is not working

**Comment by ilario** [comment]
@gmarcos87 yep, it doesn't work neither on builds.libremesh.org nor on repo.libremesh.org nor on libremesh.org
But I don't have any access to the servers, I think @p4u is the one for this.

**Comment by ilario** [comment]
Current situation of HTTPS support in our subdomains:
https://libremesh.org/ NO
https://www.libremesh.org/ NO
https://betaupdate.libremesh.org/ YES
https://chef.libremesh.org/ NO
https://ci.libremesh.org/ NO
https://wiki.libremesh.org/ NO
https://lists.libremesh.org/ YES
https://builds.libremesh.org/ NO
https://repo.libremesh.org/ NO
https://old.libremesh.org/ YES but invalid
https://downloads.libremesh.org/ NO

**Comment by aparcar** [comment]
What is the blocking thing here? https://krackattacks.com is just another reason to push this

**Comment by pedro-nonfree** [comment]
I think nearly all of us is able to solve this. Please, let's do it

**Comment by nicopace** [comment]
Don't have access to this server.
I guess @altergui or @nicoechaniz or @p4u can do it

**Comment by aparcar** [comment]
@PabloCastellano https://downloads.libremesh.org should work now

**Comment by ilario** [comment]
Thanks @aparcar and @p4u! Closing. The only couple of small things missing, are: redirect all traffic from HTTP to HTTPS on enlist in HTTPS Everywhere lists: https://www.eff.org/https-everywhere/faq#how-do-i-add-my-own-site-to-https-everywhere
