### ISSUE TITLE
Avoid the addition of non-existing repositories in distfeeds.conf

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-web#111]
Compiling LibreMesh with [the current instructions](https://github.com/libremesh/lime-web/blob/72fcb50e2787ff20c7877c532b3568249acbf94b/development.txt) results in an image including this `/etc/opkg/distfeeds.conf`:

```
src/gz openwrt_core http://downloads.openwrt.org/releases/19.07.4/targets/ath79/generic/packages
src/gz openwrt_base http://downloads.openwrt.org/releases/19.07.4/packages/mips_24kc/base
src/gz openwrt_libremap http://downloads.openwrt.org/releases/19.07.4/packages/mips_24kc/libremap
src/gz openwrt_libremesh http://downloads.openwrt.org/releases/19.07.4/packages/mips_24kc/libremesh
src/gz openwrt_luci http://downloads.openwrt.org/releases/19.07.4/packages/mips_24kc/luci
src/gz openwrt_packages http://downloads.openwrt.org/releases/19.07.4/packages/mips_24kc/packages
src/gz openwrt_routing http://downloads.openwrt.org/releases/19.07.4/packages/mips_24kc/routing
src/gz openwrt_telephony http://downloads.openwrt.org/releases/19.07.4/packages/mips_24kc/telephony
```

you can see two intruder lines: the one about libremesh (see #728) and libremap, which do not exist and cause an error like:

```
Problems with opkg update:
 * opkg_download: Failed to download http://downloads.openwrt.org/releases/19.07.4/packages/mipsel_24kc/libremap/Packages.gz, wget returned 8.
 * opkg_download: Failed to download http://downloads.openwrt.org/releases/19.07.4/packages/mipsel_24kc/libremesh/Packages.gz, wget returned 8.
```

Seems that these lines appear in the distfeeds.conf file because some repositories with this name are mentioned in the feeds.conf file used for the compilation. See:
https://github.com/openwrt/openwrt/blob/947bfc62d003ea54c13470ee6bbc9f20827592b0/package/base-files/Makefile#L201

I think that the good way to fix this is to add in the compilation instructions the following steps (during the make menuconfig section):

```
Deselect non-existing repositories
- Image configuration -> Separate feed repositories -> Enable feed libremesh
- Image configuration -> Separate feed repositories -> Enable feed libremap
```

Do you see a cleaner way to do this (e.g. a different way to use the feeds.conf file)?

**Comment by ilario** [comment]
A few users already complained about this error [here](https://lists.libremesh.org/pipermail/lime-users/2020-August/001648.html) and [here](https://lists.libremesh.org/pipermail/lime-users/2020-September/001703.html).

An alternative to expand the instructions, would be to add a [uci-defaults script to lime-system package](https://github.com/libremesh/lime-packages/tree/master/packages/lime-system/files/etc/uci-defaults) which deletes those lines in `/etc/opkg/distfeeds.conf`.

**Comment by spiccinini** [comment]
I have the following in the config
```
# CONFIG_FEED_libremap is not set
# CONFIG_FEED_libremesh is not set
```
These after being "expanded" is converted the following (at least in 18.06) in the `.config`
```
CONFIG_PER_FEED_REPO=y
CONFIG_FEED_packages=y
CONFIG_FEED_luci=y
CONFIG_FEED_routing=y
CONFIG_FEED_telephony=y
# CONFIG_FEED_libremesh is not set
# CONFIG_FEED_libremap is not set
```

I don't know if this helps somehow.

**Comment by ilario** [comment]
Yep, this is what we want to have (adding also the new `profiles` feed).
But until now we didn't suggest the users to use a custom .config but rather to go through the menuconfig and select the options there.
So the equivalent to have the lines you mentioned is to go to `Image configuration -> Separate feed repositories` and deselect those lines, I think.

The question is: do we want the user to do this (clean and nice) or do we want an uci-defaults script to delete those non-existent feeds (ugly and barbaric).

**Comment by ilario** [comment]
As no better solution appeared, I added the instructions in the development page for disabling the non-existent feeds with https://github.com/libremesh/lime-web/commit/9821e2145cf0175b498b34c3e630bb7eb9b1cadf
