### ISSUE TITLE
Improve list of communities in the home webpage

### ISSUE THREAD

**Issue by rubo77** [libremesh/lime-web#21]
Please put a link on "Several communities around the world " and link to a page with all known sites, that use libremesh

**Comment by ilario** [comment]
Does someone know where LibreMesh is in use?
It could be used in many places without us noticing...
An indication could be the Chef profiles, they're 250. 
We could send a survey to all the users of Chef via their contact email.

**Comment by nicopace** [comment]
indeed @ilario . what do you think @nicoechaniz @altergui ?

**Comment by ilario** [comment]
6 months without comments nor a single move in this direction. Let's close this issue.

**Comment by nicopace** [comment]
Well... the question from @rubo77 is interesting... showing where is being used, despite it is not easy to determine it (despite the most known ones), would open the chance to allow that conversation to happen, where communities like the Spanish guy that was using LibreMesh as a way to help fighting gentrification, would allow us to get a better understanding of the people we are working for.
I think we should solve it by putting a contact form in our site so people can come up and tell their story, and we can manually add them.
What do you think @ilario?

**Comment by ilario** [comment]
mh, nice, it would be like a blog, we could change the tab "News" in the website to "Blog" and ask for user stories. We can try...

**Comment by nicopace** [comment]
Let's have it on scope then!

**Comment by rubo77** [comment]
maybe you can add an option in the build-process to build stats of the process automatically to you, so you will get an email each time someone on earth builds:

> If you are building for an active community please consider setting this option to spread the word of your community exists

**Comment by rubo77** [comment]
For the registration form, you can use the code for the [Freifunk Api Generator](https://freifunk.net)/api-generator/ https://github.com/freifunk/api.freifunk.net

**Comment by nicopace** [comment]
@rubo77 right now we are able to know if a firmware gets built, but I feel that having a statitic of who builds something frome where is not enougth.

Which would be the use case you propose? Or, why would you think that having a page of known sites would be good?

**Comment by rubo77** [comment]
If you start a new Community, it would be great to look into others  projects, nearby.

All communities should communicate and exchange experiences

**Comment by rubo77** [comment]
Sure, there shouldn't be **in no way** be sent any information from a highly secure buildserver without question.

I thought of an **optional option** so maybe during the build process, there could popup this question: 

> Do you want to send the community information to the LibreMesh-api? [y/N]

The information could be collected and presented as a link with the information in the GET vars of the URL string, so you can send it from your own Browser.

This would make it much easyer to add data to the LibreMesh-Api

**Comment by nicopace** [comment]
@rubo77 that is information that is already being published and shared.
Also, everything on LibreMesh Chef is open for everyone to use.
If you want to build a private firmware, you better use https://github.com/libremesh/lime-sdk .

**Comment by ilario** [comment]
We can put a link in the website pointing to the network profiles repository, that list is increasingly reflecting the communities using LibreMesh:
https://github.com/libremesh/network-profiles

**Comment by ilario** [comment]
I added a line trying to solve this issue:
https://github.com/libremesh/lime-web/commit/ae858ebd37ae8d36ca301dcfae225d93c4d226ee#diff-974d4d4e5c05e40faea2b8941aea0fe8
Feel free to re-open it if you want to push for a better solution.
