### ISSUE TITLE
Fix lime-example link

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-web#36]
in this page: http://libremesh.org/docs/en_config.html
this link doesn't work:

https://github.com/libremesh/lime-packages/blob/develop/packages/lime-debug/files/etc/config/lime-example

**Comment by ilario** [comment]
the correct one would be:
https://github.com/libremesh/lime-packages/blob/develop/packages/lime-docs/files/lime-example

**Comment by ilario** [comment]
Fixed in f27946c
