### ISSUE TITLE
Does Jekyll via Docker work for you?

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-web#46]
On my laptop, executing Docker as in the readme but as root, I get an error:
```
sudo su -
systemctl start docker.service
systemctl start docker.socket
cd lime-web
export JEKYLL_VERSION=3.5
docker run --rm \
        --publish 4000:4000 \
        --volume="$PWD:/srv/jekyll" \
        -it jekyll/jekyll:$JEKYLL_VERSION \
        jekyll serve

Could not find gem 'asciidoctor (~> 1.5.0)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
```
I have asciidoctor gem locally installed but shouldn't be relevant.
Likely there's some incompatibility between our [Gemfile](/libremesh/lime-web/blob/master/Gemfile) and official Jekyll Docker image.

**Comment by nicopace** [comment]
it works for me @ilario

**Comment by spiccinini** [comment]
It also works for me. Why are you running it as root?

**Comment by ilario** [comment]
Ok, so it's ok. One day I'll try again. Thanks. Closing.
