### ISSUE TITLE
Was adding Nanostation M5 xw as supported intentional?

### ISSUE THREAD

**Issue by stephen304** [libremesh/lime-web#53]
Hi, I am working on a community mesh and in the process of looking for easily available nodes to test on, I saw that the hardware page lists both the NSM5 xm *and* the xw. The [OpenWRT page](https://wiki.openwrt.org/toh/ubiquiti/nanostationm5) for the NSM5, and [a still open issue in the OpenWRT trac](https://dev.openwrt.org/ticket/19085) hint that there may be problems with eth0 going down and not coming back up on the xw variant (xm looks like it would work 100%, but finding one seems impossible).

Looking at the history, it looks like @ilario added the xw to the list in 760f9c9a5075a206b0fb64747f39849f130def03. Perhaps him or someone else knows the status of the xw?

I was curious if the xw was tested and found to be fixed (the last comment on the trac issue hints at a fix), or whether this was a mistake when moving around this information. If the latter, it might be good to remove it until someone can say whether it's stable or not. If the former, I'd love to have some confirmation because it would be nice to be able to grab the NSM5 on display at microcenter and start trying out LibreMesh.

**Comment by ilario** [comment]
I did never experienced the mentioned bug but I remember @G10h4ck did in the past, I don't know if it's still there.
Can anyone confirm?

**Comment by G10h4ck** [comment]
Fixed in d2f65acd2b257b4de7be10c73de4888fca66400f
