### ISSUE TITLE
Please clarify the differences between the default/mini/zero builds

### ISSUE THREAD

**Issue by john-tho** [libremesh/lime-web#59]
I think it would be helpful to briefly identify the differences between the compiled image types,
on pages with links to the compiled images.

Example only, probably wrong

- default: for access points with 8MB flash
- mini: for access points with 4MB flash. Lacks ppp support & opkg package manager
- zero: for access points with 4MB flash. Lacks ppp support & UI

Or perhaps a link to the differences: https://github.com/libremesh/lime-sdk/blob/master/flavors.conf

https://github.com/libremesh/lime-web/blob/e37588650a94eaeab44ce2d8246e097886e18d6a/getit.txt#L8

https://github.com/libremesh/lime-web/blob/e37588650a94eaeab44ce2d8246e097886e18d6a/docs/en_quick_starting_guide.txt#L12

**Comment by ilario** [comment]
These names were introduced with lime-sdk and LibreMesh 17.06 release.
Likely this will not exist anymore in the next release.
