### ISSUE TITLE
Please clarify prefixes ap, apname, adhoc for _ssid

### ISSUE THREAD

**Issue by john-tho** [libremesh/lime-web#60]
The web site does not clearly explain what the ap, apname, adhoc prefixes are used for in the LibreMesh config

Example (probably wrong):
- apname_ssid: Per access point unique SSID to avoid roaming (switching) between various access points that share an SSID
  https://github.com/libremesh/lime-packages/commit/a17e6170e838a29dcd0b65bde1fa0906b0898333
- ap_ssid: ?The SSID for consumer device access
  This is used as network / cloud identifier, and therefore BATADV VLAN is based on this setting.
  Access points that share the same ap_ssid will act like a single LAN
- adhoc_ssid: ?The mesh link used between access points

https://github.com/libremesh/lime-packages/blob/develop/packages/lime-docs/files/lime-example

https://github.com/libremesh/lime-web/blob/e37588650a94eaeab44ce2d8246e097886e18d6a/docs/en_config.txt#L103

https://github.com/libremesh/lime-web/blob/e37588650a94eaeab44ce2d8246e097886e18d6a/howitworks.txt#L53

A mention that this is the `config lime wifi` `ap_ssid` might make it more clear?

Cheers

**Comment by sanadora** [comment]
Hello! 
I would like to collaborate on this issue, but I fear it is not clear to me where the clarifications are needed...
Is it in the `lime-example` file of the nodes? or in some page of the web?

**Comment by ilario** [comment]
Hey @sanadora! Thanks and sorry for the late answer!
Yes, the places where that piece of documentation would be most needed are:

the lime-example file
https://github.com/libremesh/lime-packages/blob/7bb258ef33838da443bb0e6fa7bdf8b5e694deeb/packages/lime-docs/files/lime-example#L78-L82

the website documentation about configuration file
https://github.com/libremesh/lime-web/blob/master/docs/en_config.txt#L127-L179

Thanks!!!!
