### ISSUE TITLE
libremesh.org inaccessible over advertised IPv6

### ISSUE THREAD

**Issue by romanrm** [libremesh/lime-web#64]
```
$ curl -v6 libremesh.org
* Rebuilt URL to: libremesh.org/
*   Trying 2a00:1508:1:f001::106...
* TCP_NODELAY set
* connect to 2a00:1508:1:f001::106 port 80 failed: Connection timed out
* Failed to connect to libremesh.org port 80: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to libremesh.org port 80: Connection timed out
```

**Comment by romanrm** [comment]
5 months later, nothing changed.

**Comment by ilario** [comment]
I think it's perceived as a low priority issue, but I agree with you that we should have that.
Maybe @p4u @altergui @nicoechaniz know how to achieve this?

**Comment by romanrm** [comment]
> I think it's perceived as a low priority issue, but I agree with you that we should have that.

The issue is not that you do not have IPv6, the problem is that your site claims to have it:

libremesh.org has address 109.69.10.46
libremesh.org has IPv6 address 2a00:1508:1:f001::106

But in reality that is broken (not responding on IPv6), which causes issues for IPv6-only users, and for users on various kinds of proxy software, making your website completely inaccessible to them: https://romanrm.hk/2019-02-26T094725Z-lm.png

Some portion of your visitors cannot reach the site at all because of this misconfiguration. If you cannot implement IPv6 properly, then you should at least remove the AAAA record from DNS.

Thanks

**Comment by ilario** [comment]
Wow, so this is serious, please @p4u @altergui @nicoechaniz have a look at this

**Comment by p4u** [comment]
The IPv6 connection and the libremesh server is actually managed by @nicoechaniz, while the IPv6 problem is not fixed, I've moved the AAAA registy to ipv6.libremesh.org, so now only IPv4 is available.

Thanks for reporting!

**Comment by ilario** [comment]
> I've moved the AAAA registy to ipv6.libremesh.org, so now only IPv4 is available.

In my opinion this solves the issue :)
