### ISSUE TITLE
Better way to list supported hardware

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-web#72]
Currently we have a **very small list of officially supported router models** [here](https://libremesh.org/docs/hardware/index.html).

It would be amazing to **replace** the quite useless table with some **general criteria**.

For example:

1. OpenWrt support is needed.
2. Routers supported within OpenWrt targets:
    1. ar71xx, yyyy, ... support all LibreMesh features with default configuration
    2. zzzzz, ... support LibreMesh but require manual configuration for just one interface per radio
    3. ttttttt, ... support LibreMesh but the radios does not support ieee802.11s mesh. As an alternative, adhoc, AP and client can be used
    4. nnnnn, .... support LibreMesh but the radios does not support neither ieee802.11s nor adhoc mesh. As an alternative, AP and client can be used
3. The minimum amount of RAM memory is 32 MB
4. The minimum amount of flash memory is:
    1. 8 MB for lime-defaults flavor and network profiles based on it
    2. 4 MB for lime-mini and lime-zero flavors and network profiles based on these

Do you think is possible? @G10h4ck @p4u @nicopace @nicoechaniz @aparcar @dangowrt @altergui

**Comment by G10h4ck** [comment]
Yeah I was always against maintaining our own specific TOH because i tought it was impossible to maintain by us, and always preferred this critaria list option + link to openwrt TOH

**Comment by ilario** [comment]
@G10h4ck great, can we start sketching the criteria list? Is what I put a good skeleton?

**Comment by G10h4ck** [comment]
Seems a good start to me, also take in account that some routers may have one CPU architecture like ar71xx which usually suggest support for both adhoc and ap on same radio, but could have some radio  (outside of the SoC) based on other chip/driver which doesn't support that

**Comment by nicopace** [comment]
The wikidevi database can be queried, and allows to say:
* all openwrt supported devices
* only those that have 8MB of storage or more
* only those that have 32MB of ram or more
* only those that have Atheros 9k radios

Right now it is not working (?), but we could put a cron that ddownloads
the sampe one time per day, and list that in our site.

The url is www.wikidevi.com

Another part that is tricky is downloading the right image for your
board. Hope we can do something about that in this process.

Regards,

**Comment by nicopace** [comment]
This can be one:

https://wikidevi.com/w/index.php?title=Special%3AAsk&q=%5B%5BThird+party+firmware+supported%3A%3AOpenWrt%5D%5D+%5B%5BCPU1+brand%3A%3AAtheros%5D%5D+%5B%5BWI1+chip1+brand%3A%3AAtheros%5D%5D+%5B%5BSupported+802dot11+protocols%3A%3Abgn%5D%5D%0D%0A&po=%3FFCC+ID%0D%0A%3FSupported+802dot11+protocols%0D%0A%3FCPU1+model%0D%0A%3FFLA1+amount%0D%0A%3FRAM1+amount%0D%0A%3FWI1+chip1+model%0D%0A%3FWI1+chip2+model%0D%0A%3FWI2+chip1+model%0D%0A%3FWI2+chip2+model%0D%0A%3FUSB+ports%0D%0A%3FLAN+speed%0D%0A%3FWAN+ports%0D%0A%3FLAN+ports%0D%0A&eq=yes&p%5Bformat%5D=broadtable&sort_num=&order_num=ASC&p%5Blimit%5D=10000&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=Page+name&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bclass%5D=sortable+wikitable+smwtable&p%5Bsep%5D=&eq=yes

this is the filter applied:

[[Third party firmware supported::OpenWrt]] [[CPU1 brand::Atheros]]
[[WI1 chip1 brand::Atheros]] [[Supported 802dot11 protocols::bgn]]


Not showing some of them, but we can tune the database.
Also, the data is open data:

https://archive.org/details/wikidevi

If we work on the data, we can work on a javascript implementation.

Regards

**Comment by ilario** [comment]
Regarding the flash and RAM minimum limits we can reference OpenWrt page: https://openwrt.org/supported_devices/432_warning

**Comment by decentral1se** [comment]
Good idea on the "criteria". It did feel unclear to search for hardware and then to not really know what makes one hardware work and the other not. So, I like this idea. Btw, I added the OpenWRT link on this PR: https://github.com/libremesh/lime-web/pull/75, might be useful for others.

**Comment by ilario** [comment]
https://openwrt.org/toh/views/toh_standard_all?dataflt[0]=supported+current+rel_%3D19.07.4&dataflt[Target_target*~]=ath79&dataflt[WLAN+5.0GHz*~]=n&dataflt[WLAN+2.4GHz*~]=n

Here I applied a few filters:
supported by OpenWrt 19.07.4
included in target ATH79
has 2.4 GHz radio
has 5 GHz radio

Which results in 99 models, all with at least 8 MB flash and at least 64 MB RAM.
Do you like this list?
Then we should warn the users to check how easy/prohibitive is the flashing.

**Comment by spiccinini** [comment]
The list seems good to me!

**Comment by spiccinini** [comment]
We can say that the list is 
suggested hardware and that not all models are being tested.

**Comment by ilario** [comment]
Yessss

**Comment by ilario** [comment]
Please check #124

**Comment by ilario** [comment]
Fixed in #124
