### ISSUE TITLE
Replace Riot with Mattermost link in Communication page

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-web#73]
Seems that Riot/Matrix (#libremesh-dev:matrix.guifi.net federated with other Matrix servers) is not accepted as official chatroom, while Mattermost (on https://mattermost.altermundi.net) is the official one ([ref](https://github.com/libremesh/lime-packages/pull/412#issuecomment-430184975))

The blocking problem is that: 

> For the public chatroom both registration and invitation is required. There is no way to ask for an invitation in the mattermost interface. This should be changed in order to have a public, official and accesible chat IMHO ([ref](https://github.com/libremesh/lime-packages/pull/412#issuecomment-431950614))

After this, we will need to include the Mattermost link also in lime-packages readme and other occurrences of the contact details.

**Comment by ilario** [comment]
This is so easy to solve that I cannot understand why it has not been done before (unless admins disagree with discussion on libremesh/lime-packages#412...?).

Currently new users receive a

`signup_team.no_open_teams: No teams are available to join. Please ask your administrator for an invite.`

just after the login page.

In order to have "chaosmonekeys" team listed there it is enough to activate "Allow anyone to join this team". This can be done by Team Administrators:
https://docs.mattermost.com/help/settings/team-settings.html#allow-anyone-to-join-this-team

**Comment by aparcar** [comment]
@gmarcos87 ping, please do so. Private mattermost channels are still private

**Comment by ilario** [comment]
@aparcar just a correction: _Public_ Mattermost channels still require admission. Sure there are also private Mattermost channels but that's not a problem I think.

**Comment by p4u** [comment]
I'd prefer Matrix rather than Mattermost. Mainly cause I use Matrix for many other stuff while Mattermost would be only for LibreMesh. Many communities around are moving to Matrix, I don't understand what are the points against it, so my vote is for Matrix (as a core dev). However as I'm not very active ultimately, I don't want to block any decision. But I doubt I'd be able to follow Mattermost (however anyway I think we all agree that the main communication channel is the mailing list).

**Comment by ilario** [comment]
I also don't care about whether Matrix or Mattermost (but seems that a few core developers hate Matrix).
What I do care is transparency: it has to be defined if the project management is open, by a community (preferably) or closed, by a closed collective.
The lack of transparency is one of the causes of LEDE fork a few years ago, let's learn from history, please.
In the case the management is open, the actual communication channel (which is clearly not lime-dev as it is completely inactive) has to be public and matching the communication info on the website.

**Comment by decentral1se** [comment]
Hey folks, pity you don't have a public accessible chat anymore (AFAICT, checking https://github.com/libremesh/lime-packages/pull/412#issuecomment-431950614). Mailing list is good and all but IM is useful to build a community ... I do lurk the IRC already but not much happening unfortunately. Anyway, just wanted to give some feedback.

**Comment by wfleurant** [comment]
well, bridge support for Matrix, iRC, Mattermost would alieviate fragmented communications, no?

**Comment by ilario** [comment]
Update from @nicoechaniz:

> mattermost is an internal communication channel among developers. That's the idea. Any public-facing channels are welcome as long as we can have some presence so they don't appear deserted.

**Comment by nicopace** [comment]
though it hasn't been the official mean of communication, the mattermost channel has been running successfully for some time alredy.

To summarize opinions:
* there was a proposal to use public mattermost instance
* there is an unofficial quite used instance already working
* there are suggestions for other options, but no blockers for the one already working

Based on this, and as there is no blocking position, please @gmarcos87 do put it public so we can update the site.

Thanks

**Comment by nicoechaniz** [comment]
This comment is still valid: 

mattermost is an internal communication channel among developers. That's the idea. Any public-facing channels are welcome as long as we can have some presence so they don't appear deserted.
