### ISSUE TITLE
Incorrect Mailing Lists URLs in side_nav

### ISSUE THREAD

**Issue by kjuanman** [libremesh/lime-web#8]
http://lists.libre-mesh.org/mailman/listinfo/dev should be https://lists.libremesh.org/mailman/listinfo/lime-dev
http://lists.libre-mesh.org/mailman/listinfo/users should be https://lists.libremesh.org/mailman/listinfo/lime-users

regards

**Comment by altergui** [comment]
On 03/10/16 17:27, kjuanman wrote:
> http://lists.libre-mesh.org/mailman/listinfo/dev should be
> https://lists.libremesh.org/mailman/listinfo/lime-dev
> http://lists.libre-mesh.org/mailman/listinfo/users should be
> https://lists.libremesh.org/mailman/listinfo/lime-users
> 
> regards
> 

fixed with commit c61c39439, thanks
